
const COMMUNITIES=[
{id:"beaufort-sc",name:"Beaufort, SC",type:"Coastal / military-friendly",score:73,label:"🌱 Good Fit",summary:"Beaufort is a strong fit for families who value coastal living, military community, outdoor recreation, and local identity. The tradeoffs are job-market depth, childcare planning, weather/storm risk, and neighborhood-specific safety research.",categories:[
{key:"safety",name:"🛡️ Safety & Stability",score:72,quick:"Generally workable, but exact neighborhood research matters.",stats:[["City crime source","Beaufort Police annual reports"],["County crime source","BCSO NIBRS summaries"],["Neighborhood-level parsing","Not connected yet"]],notes:["Use city police annual reports for city-level trends.","Use Beaufort County Sheriff reports for county/unincorporated areas.","Next step: parse incident counts and recent calls into comparable neighborhood data."],sources:["https://www.cityofbeaufort.org/592/Annual-Reports","https://bcso.net/public-information/data-and-statistics/"]},
{key:"schools",name:"🏫 Schools",score:78,quick:"Good and improving, but school zone matters.",stats:[["Good/Excellent schools","53%"],["Prior year","44%"],["Graduation rate","88.6%"],["College/career ready","82.8%"]],notes:["BCSD reported improvement in 2024 school report cards.","No BCSD school was rated Unsatisfactory for the first time since 2018."],sources:["https://www.beaufortschools.net/about-us/whats-new-default-board/~board/whats-new/post/sc-department-of-education-releases-2024-report-cards-for-schools-districts","https://screportcards.com/"]},
{key:"financial",name:"💰 Financial Wellbeing",score:64,quick:"Can work well, but housing and insurance/tax details need careful review.",stats:[["Median household income","$86,573"],["Median home value","$455,600"],["Median gross rent","$1,653"],["Owner cost with mortgage","$2,030"]],notes:["Income is strong, but housing costs are high.","Storm/insurance/tax details should be researched before buying."],sources:["https://www.census.gov/quickfacts/fact/table/beaufortcountysouthcarolina/SBO040223","https://www.cityofbeaufort.org/m/faq?cat=39#question-200"]},
{key:"jobs",name:"💼 Job Market",score:71,quick:"Good for some fields, limited for others.",stats:[["County employment, 2023","59,121"],["Employment growth","2.6%"],["Mean commute","23.6 minutes"]],notes:["Stronger around military, healthcare, education, tourism, hospitality, retail, and remote/regional work."],sources:["https://installations.militaryonesource.mil/military-installation/mcrd-parris-island/military-and-family-support-center/employment","https://www.bmhsc.org/careers"]},
{key:"childcare",name:"👶 Childcare",score:64,quick:"Plan early and verify openings directly.",stats:[["Data status","Provider search not connected yet"],["Next source","SC DSS childcare licensing"],["Family action","Call providers early"]],notes:["The live app should show license status, ages served, pricing, openings, waitlist, reviews, and contact buttons."],sources:["https://dss.sc.gov/child-care/"]},
{key:"community",name:"🤝 Community",score:82,quick:"Strong community identity, especially for military and outdoor-oriented families.",stats:[["Veterans","16,866"],["Population growth","9.3%"],["Military fit","MCRD Parris Island + MCAS Beaufort region"]],notes:["Strong veteran/military presence and outdoor community culture."],sources:["https://www.census.gov/quickfacts/fact/table/beaufortcountysouthcarolina/SBO040223","https://www.beaufortsc.org/"]},
{key:"quality",name:"😊 Quality of Life",score:87,quick:"Excellent lifestyle fit if you like coastal/outdoor living.",stats:[["Mean commute","23.6 minutes"],["Strengths","Water, parks, history, events"],["Weather reality","Heat, humidity, storms"]],notes:["Families should weigh outdoor benefits against heat, storms, and insurance considerations."],sources:["https://discoversouthcarolina.com/beaufort","https://www.beaufortsc.org/"]},
{key:"connectivity",name:"📶 Connectivity",score:92,quick:"Generally strong, but verify by exact address.",stats:[["Broadband subscription","94.0%"],["Households with computer","97.2%"],["Address-level check","Required"]],notes:["Use FCC National Broadband Map for exact address availability."],sources:["https://broadbandmap.fcc.gov/","https://www.census.gov/quickfacts/fact/table/beaufortcountysouthcarolina/SBO040223"]}
],reality:["Job options can be narrower depending on career field.","Childcare should be verified early.","Heat, humidity, storms, and insurance should be part of the plan.","Safety varies by exact neighborhood."]},
{id:"mechanicsburg-pa",name:"Mechanicsburg, PA",type:"Suburban / family-oriented",score:84,label:"🌟 Excellent Fit",summary:"Sample community profile used for comparison.",categories:[],reality:["Sample data only."]},
{id:"winchester-va",name:"Winchester, VA",type:"Small city / commuter-friendly",score:80,label:"🚀 Strong Fit",summary:"Sample community profile used for comparison.",categories:[],reality:["Sample data only."]},
{id:"lititz-pa",name:"Lititz, PA",type:"Small town / highly family-oriented",score:86,label:"🌟 Excellent Fit",summary:"Sample community profile used for comparison.",categories:[],reality:["Sample data only."]}
];

const OPPORTUNITIES=[
{cat:"youth",icon:"⚾",title:"Youth Baseball",items:[["Beaufort County youth sports","View programs"],["Local recreation leagues","View registration"],["Baseball clinics","View clinics"]]},
{cat:"childcare",icon:"👶",title:"Childcare",items:[["SC DSS childcare search","View providers"],["Local daycare shortlist","Schedule tours"],["After-school care","View options"]]},
{cat:"jobs",icon:"💼",title:"Jobs",items:[["Beaufort Memorial careers","View jobs"],["Military spouse employment","View resources"],["Remote work options","View remote jobs"]]},
{cat:"community",icon:"🤝",title:"Community Groups",items:[["Military family groups","View groups"],["Parent events","View events"],["Volunteer opportunities","View options"]]},
{cat:"connectivity",icon:"📶",title:"Connectivity",items:[["FCC broadband map","Check address"],["Cell carrier comparison","Compare carriers"]]}
];
